[package]
name = "nitron-client"
version = "0.1.0"
edition = "2021"
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = "*"
specs-derive = "*"

[dependencies.sdl2]
version = "*"
default-features = false
features = ["image", "ttf"]